packages:
  - api
  - authentication-server
  - core/alerts/*
  - core/attachments/*
  - core/authentication/*
  - core/backends/*
  - core/browser/*
  - core/configuration/*
  - core/collaboration/*
  - core/date/*
  - core/document/*
  - core/extra-tabs/*
  - core/file-preview/*
  - core/fn-utils
  - core/hierarchy/*
  - core/history/*
  - core/icons
  - core/info-actions/*
  - core/link-suggest/*
  - core/macros/*
  - core/messages/messages-macros
  - core/model/model-api
  - core/model/model-click-listener
  - core/model/model-local-url
  - core/model/model-reference/*
  - core/model/model-remote-url/*
  - core/model/model-remote-url/model-remote-url-filesystem/*
  - core/navigation-tree/*
  - core/nextcloud/*
  - core/page/*
  - core/page-actions/*
  - core/reactivue
  - core/rename/*
  - core/settings/*
  - core/uiextension/*
  - core/uniast/*
  - core/user/*
  - core/xwiki/*
  - core/wiki-config/*
  - dev/*
  - ds/api
  - ds/shoelace
  - ds/vuetify
  - editors/*
  - electron
  - electron/authentication/authentication-github/*
  - electron/authentication/authentication-nextcloud/*
  - electron/authentication/authentication-xwiki/*
  - electron/main
  - electron/preload
  - electron/renderer
  - electron/storage
  - electron/state
  - electron/browser
  - electron/link-suggest/*
  - electron/settings/*
  - extension-manager
  - extensions/menubuttons
  - lib
  - realtime
  - sharedworker/api
  - sharedworker/impl
  - skin
  - sources/xwiki/mock-server
  - utils/inversify
  - web
  - xwiki/remoteinlineeditor

catalog:
  '@eslint/config-helpers': 0.5.2
  '@eslint/eslintrc': 3.3.3
  '@eslint/js': 9.39.2
  '@hocuspocus/provider': 2.15.3
  '@hocuspocus/server': 2.15.3
  '@microsoft/api-extractor': 7.57.1
  '@microsoft/tsdoc': 0.16.0
  '@microsoft/tsdoc-config': 0.18.0
  '@playwright/test': 1.57.0
  '@shoelace-style/shoelace': 2.20.1
  '@types/async-lock': 1.4.2
  '@types/express': 5.0.6
  '@types/express-ws': 3.0.6
  '@types/js-cookie': 3.0.6
  '@types/lodash-es': 4.17.12
  '@types/node': 24.10.13
  '@types/sharedworker': 0.0.216
  '@types/xml-escape': 1.1.3
  '@typescript-eslint/eslint-plugin': 8.56.0
  '@typescript-eslint/parser': 8.56.0
  '@vitejs/plugin-vue': 6.0.4
  '@vitest/coverage-v8': 4.0.18
  '@vue/test-utils': 2.4.6
  '@xwiki/platform-api': ^18.2.0-0
  '@xwiki/platform-attachments-api': ^18.2.0-0
  '@xwiki/platform-attachments-default': ^18.2.0-0
  '@xwiki/platform-authentication-api': ^18.2.0-0
  '@xwiki/platform-backend-api': ^18.2.0-0
  '@xwiki/platform-collaboration-api': ^18.2.0-0
  '@xwiki/platform-configuration-api': ^18.2.0-0
  '@xwiki/platform-document-api': ^18.2.0-0
  '@xwiki/platform-dsapi': ^18.2.0-0
  '@xwiki/platform-editors-blocknote-headless': ^18.2.0-0
  '@xwiki/platform-fn-utils': ^18.2.0-0
  '@xwiki/platform-icons': ^18.2.0-0
  '@xwiki/platform-link-suggest-api': ^18.2.0-0
  '@xwiki/platform-macros-api': ^18.2.0-0
  '@xwiki/platform-macros-service': ^18.2.0-0
  '@xwiki/platform-model-api': ^18.2.0-0
  '@xwiki/platform-model-reference-api': ^18.2.0-0
  '@xwiki/platform-model-remote-url-api': ^18.2.0-0
  '@xwiki/platform-navigation-tree-api': ^18.2.0-0
  '@xwiki/platform-uniast-api': ^18.2.0-0
  '@xwiki/platform-uniast-markdown': ^18.2.0-0
  async-lock: 1.4.1
  axios: 1.13.5
  comlink: 4.4.2
  concurrently: 9.2.1
  dayjs: 1.11.19
  dexie: 4.3.0
  dotenv: 17.2.4
  electron: 40.1.0
  electron-builder: 26.0.12
  electron-store: 11.0.2
  esbuild: 0.27.3
  eslint: 9.39.3
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-headers: 1.3.3
  eslint-plugin-import: 2.32.0
  eslint-plugin-prettier: 5.5.5
  eslint-plugin-promise: 7.2.1
  eslint-plugin-tsdoc: 0.5.0
  eslint-plugin-vue: 10.8.0
  express: 5.2.1
  express-ws: 5.0.2
  fast-xml-parser: 5.3.4
  filesize.js: 2.0.0
  globals: 17.3.0
  happy-dom: 20.6.3
  inversify: 7.11.0
  jiti: 2.6.1
  js-cookie: 3.0.5
  lib0: 0.2.117
  lodash-es: 4.17.23
  mime: 4.1.0
  nodemon: 3.1.13
  nx: 22.5.1
  pinia: 3.0.4
  prettier: 3.8.1
  publint: 0.3.17
  reflect-metadata: 0.2.2
  rimraf: 6.1.3
  ts-essentials: 10.1.1
  ts-node: 10.9.2
  tsx: 4.21.0
  typescript: 5.9.3
  typescript-eslint: 8.56.0
  vite: 7.3.1
  vite-plugin-css-injected-by-js: 3.5.2
  vite-plugin-dts: 4.5.4
  vite-plugin-node: 7.0.0
  vitest: 4.0.18
  vitest-mock-extended: 3.1.0
  vue: 3.5.28
  vue-eslint-parser: 10.4.0
  vue-i18n: 11.2.8
  vue-router: 4.6.4
  vue-tsc: 3.2.4
  vuetify: 3.11.8
  xml-escape: 1.1.0
  y-websocket: 3.0.0
  yaml: 2.8.2
  yjs: 13.6.29

catalogMode: strict

cleanupUnusedCatalogs: true
