packages:
  - api
  - authentication-server
  - core/alerts/*
  - core/attachments/*
  - core/authentication/*
  - core/backends/*
  - core/browser/*
  - core/configuration/*
  - core/collaboration/*
  - core/date/*
  - core/document/*
  - core/extra-tabs/*
  - core/file-preview/*
  - core/fn-utils
  - core/hierarchy/*
  - core/history/*
  - core/icons
  - core/info-actions/*
  - core/link-suggest/*
  - core/macros/*
  - core/markdown/*
  - core/model/model-api
  - core/model/model-click-listener
  - core/model/model-local-url
  - core/model/model-reference/*
  - core/model/model-remote-url/*
  - core/model/model-remote-url/model-remote-url-filesystem/*
  - core/navigation-tree/*
  - core/page/*
  - core/page-actions/*
  - core/reactivue
  - core/rename/*
  - core/settings/*
  - core/uiextension/*
  - core/uniast/*
  - core/user/*
  - core/xwiki/*
  - core/wiki-config/*
  - dev/*
  - ds/api
  - ds/shoelace
  - ds/vuetify
  - editors/*
  - electron
  - electron/authentication/authentication-github/*
  - electron/authentication/authentication-nextcloud/*
  - electron/authentication/authentication-xwiki/*
  - electron/main
  - electron/preload
  - electron/renderer
  - electron/storage
  - electron/state
  - electron/browser
  - electron/link-suggest/*
  - electron/settings/*
  - extension-manager
  - extensions/menubuttons
  - lib
  - realtime
  - sharedworker/api
  - sharedworker/impl
  - skin
  - sources/xwiki/mock-server
  - utils/inversify
  - web
  - xwiki/remoteinlineeditor

catalog:
  '@blocknote/core': 0.35.0
  '@blocknote/mantine': 0.35.0
  '@blocknote/react': 0.35.0
  '@changesets/cli': 2.29.7
  '@eslint/config-helpers': 0.4.1
  '@eslint/eslintrc': 3.3.1
  '@eslint/js': 9.38.0
  '@hocuspocus/provider': 2.15.3
  '@hocuspocus/server': 2.15.3
  '@mantine/core': 8.3.5
  '@mantine/hooks': 8.3.5
  '@microsoft/api-extractor': 7.53.3
  '@microsoft/tsdoc': 0.15.1
  '@microsoft/tsdoc-config': 0.17.1
  '@playwright/experimental-ct-react': 1.56.1
  '@playwright/test': 1.56.1
  '@shoelace-style/shoelace': 2.20.1
  '@types/async-lock': 1.4.2
  '@types/express': 5.0.5
  '@types/express-ws': 3.0.6
  '@types/js-cookie': 3.0.6
  '@types/lodash-es': 4.17.12
  '@types/markdown-it': 14.1.2
  '@types/mdast': 4.0.4
  '@types/node': 24.9.1
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@types/sharedworker': 0.0.189
  '@types/xml-escape': 1.1.3
  '@typescript-eslint/eslint-plugin': 8.46.2
  '@typescript-eslint/parser': 8.46.2
  '@vitejs/plugin-react': 5.1.0
  '@vitejs/plugin-vue': 6.0.1
  '@vitest/coverage-v8': 4.0.4
  '@vue/test-utils': 2.4.6
  async-lock: 1.4.1
  axios: 1.13.0
  bootstrap-icons: 1.13.1
  comlink: 4.4.2
  concurrently: 9.2.1
  dayjs: 1.11.18
  dexie: 4.2.1
  dotenv: 17.2.3
  electron: 39.0.0
  electron-builder: 26.0.12
  electron-store: 11.0.2
  esbuild: 0.25.11
  eslint: 9.38.0
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-headers: 1.3.3
  eslint-plugin-import: 2.32.0
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-promise: 7.2.1
  eslint-plugin-tsdoc: 0.4.0
  eslint-plugin-vue: 10.5.1
  eventemitter3: 5.0.1
  express: 5.1.0
  express-ws: 5.0.2
  fast-xml-parser: 5.3.0
  filesize.js: 2.0.0
  globals: 16.4.0
  happy-dom: 20.0.8
  i18next: 25.5.3
  inversify: 7.10.4
  jiti: 2.6.1
  js-cookie: 3.0.5
  lib0: 0.2.114
  lodash-es: 4.17.21
  markdown-it: 14.1.0
  mdast-util-gfm-strikethrough: 2.0.0
  mdast-util-gfm-table: 2.0.0
  mdast-util-gfm-task-list-item: 2.0.0
  micromark-extension-gfm-strikethrough: 2.1.0
  micromark-extension-gfm-table: 2.1.1
  micromark-extension-gfm-task-list-item: 2.1.0
  mime: 4.1.0
  nodemon: 3.1.10
  nx: 22.0.1
  pinia: 3.0.2
  postcss: 8.5.6
  postcss-preset-mantine: 1.18.0
  postcss-simple-vars: 7.0.1
  prettier: 3.6.2
  publint: 0.3.15
  react: 19.2.0
  react-dom: 19.2.0
  react-i18next: 16.2.0
  react-icons: 5.5.0
  reflect-metadata: 0.2.2
  remark-parse: 11.0.0
  rimraf: 6.0.1
  ts-essentials: 10.1.1
  ts-node: 10.9.2
  tsx: 4.20.6
  typescript: 5.9.3
  typescript-eslint: 8.46.2
  unified: 11.0.5
  utility-types: 3.11.0
  vite: 7.1.12
  vite-plugin-css-injected-by-js: 3.5.2
  vite-plugin-dts: 4.5.4
  vite-plugin-node: 7.0.0
  vitest: 4.0.4
  vitest-mock-extended: 3.1.0
  vue: 3.5.22
  vue-eslint-parser: 10.2.0
  vue-i18n: 11.1.12
  vue-router: 4.6.3
  vue-tsc: 3.1.2
  vuetify: 3.10.7
  xml-escape: 1.1.0
  y-websocket: 3.0.0
  yaml: 2.8.1
  yjs: 13.6.27

catalogMode: strict

cleanupUnusedCatalogs: true
